# Generated by Django 6.0.2 on 2026-02-24 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DisasterPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disaster_type', models.CharField(choices=[('Flood', 'Flood'), ('Heatwave', 'Heatwave'), ('Landslide', 'Landslide')], max_length=50)),
                ('risk_score', models.FloatField()),
                ('confidence', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('channel', models.CharField(choices=[('SMS', 'SMS'), ('Voice', 'Voice'), ('CellBroadcast', 'CellBroadcast')], max_length=50)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Sent', max_length=50)),
                ('prediction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disaster.disasterprediction')),
            ],
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('population', models.IntegerField()),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disaster.state')),
            ],
        ),
        migrations.CreateModel(
            name='ResourceRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disaster_type', models.CharField(max_length=50)),
                ('evacuees_estimated', models.IntegerField()),
                ('food_packets', models.IntegerField()),
                ('water_litres', models.IntegerField()),
                ('medical_teams', models.IntegerField()),
                ('rescue_boats', models.IntegerField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disaster.village')),
            ],
        ),
        migrations.AddField(
            model_name='disasterprediction',
            name='village',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disaster.village'),
        ),
        migrations.CreateModel(
            name='VolunteerFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporter_name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('report', models.TextField()),
                ('severity', models.CharField(max_length=50)),
                ('verified', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disaster.village')),
            ],
        ),
    ]
